import os, re
src = open('main.py', encoding='utf-8-sig').read()
deps_raw = open('requirements.txt', encoding='utf-8-sig').read().strip().split('\n')
deps = []
for d in deps_raw:
    if d and d.strip() and d not in deps:
        deps.append(d)
templates = sorted(os.listdir('templates'))
try:
    roadmap_lines = [l for l in open('ROADMAP_V2.md', encoding='utf-8').read().split('\n') if '| V' in l and '|---|---|' not in l]
except:
    roadmap_lines = []
def collect_apis(code):
    apis = []
    for line in code.split('\n'):
        m = re.search(r"@app\.(get|post|put|delete)\s*\(\s*[\"'](/api/[^\"')]+)[\"']", line)
        if m:
            apis.append((m.group(1).upper(), m.group(2)))
    return apis
def collect_tables(code):
    tables = []
    for line in code.split('\n'):
        m = re.search(r'CREATE TABLE IF NOT EXISTS (\w+)', line)
        if m:
            tables.append(m.group(1))
    indexes = []
    for line in code.split('\n'):
        m = re.search(r'CREATE INDEX IF NOT EXISTS (\w+)', line)
        if m:
            indexes.append(m.group(1))
    return tables, indexes
apis = collect_apis(src)
api_apis = [(m, p) for m, p in apis if '/api/' in p]
tables, indexes = collect_tables(src)
lines = []
def w(t=''): lines.append(t)
w('# Project Context')
w('')
w('> Auto-generated by generate_context.py | Updated: auto')
w('')
w('## 1. Project Summary')
w('')
w('Worldview Database Management System v1.15.0')
w('An AI-native worldbuilding platform.')
w('Tech stack: FastAPI + SQLite (WAL) + Jinja2')
w('')
w('## 2. Architecture')
w('')
w('| Component | Choice |')
w('|---|---|')
w('| Backend | FastAPI (Python 3.10) |')
w('| Database | SQLite 3 (WAL mode) |')
w('| Rendering | Jinja2 SSR |')
w('| Auth | X-API-Key header |')
w('| Vector Store | sqlite-vec (V1.1) |')
w('| Cache | diskcache (V1.3) |')
w('| Graph DB | Neo4j (V1.5) |')
w('')
w('## 3. Database')
w('')
w('Database: novel_world_zh.db')
w('')
w('### Tables')
for t in tables:
    w(f'- {t}')
w('')
w('### Indexes')
for idx in indexes:
    w(f'- {idx}')
w('')
w('## 4. API Endpoints')
w('')
w('| Method | Path |')
w('|---|---|')
for method, path in api_apis:
    w(f'| {method} | {path} |')
w('')
w('## 5. Dependencies')
for d in deps:
    w(f'- {d}')
w('')
w('## 6. Version Roadmap')
w('')
w('Current: v1.15.0')
w('')
w('| Version | Focus |')
w('|---|---|')
for rl in roadmap_lines:
    w(rl)
w('')
w('## 7. Templates')
for t in templates:
    w(f'- {t}')
w('')
w('---')
w('Generated by generate_context.py | To regenerate: python generate_context.py')
script = '\n'.join(lines)
with open('project_context.md', 'w', encoding='utf-8') as f:
    f.write(script)
print('OK -', len(script), 'bytes')
